export default {
	products: [
	{
		id: 0,
		SKU: "000001",
		name: "Leeds Rhinos 2020-21 Home Shirt",
		category: "Off-Field",
		team: ["Leeds Rhinos", "Sale"],
		price: 44.99,
		imageOne: "/images/Product1.jpg",
		imageTwo: "/images/Product2.jpg",
		sale: 1,
	},
	{
		id: 1,
		SKU: "000002",
		name: "Gloucester 2020-21 Away Shirt",
		category: "Off-Field",
		team: "Gloucester Rugby",
		price: 44.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 0,
	},
	{
		id: 2,
		SKU: "000003",
		name: "Gloucester 2019-20 Home Shirt",
		category: "Off-Field",
		team: "Gloucester Rugby",
		price: 24.99,
		imageOne: "/images/Product1.jpg",
		imageTwo: "/images/Product2.jpg",
		sale: 0,
	},
	{
		id: 3,
		SKU: "000004",
		name: "Doncaster Rovers 2019-20 Away Shirt",
		category: "Off-Field",
		team: ["Doncaster Rovers", "Sale"],
		price: 12.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 0,
	},
	{
		id: 4,
		SKU: "000005",
		name: "Gloucester 2020-21 Home Shirt",
		category: "Off-Field",
		team: "Gloucester Rugby",
		price: 15.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 1,
	},
	{
		id: 5,
		SKU: "000006",
		name: "Gloucester 2020-21 Tee 1",
		category: "Off-Field",
		team: "Gloucester Rugby",
		price: 22.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 0,
	},
	{
		id: 6,
		SKU: "000007",
		name: "Gloucester 2020-21 Tee 2",
		category: "Off-Field",
		team: ["Gloucester Rugby", "Sale"],
		price: 40.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 1,
	},
	{
		id: 7,
		SKU: "000008",
		name: "Gloucester 2020-21 Tee 3",
		category: "Off-Field",
		team: ["Gloucester Rugby", "Sale"],
		price: 2.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 0,
	},
	{
		id: 8,
		SKU: "000009",
		name: "Oxen Polo 1",
		category: "Off-Field",
		team: "Oxen",
		price: 41.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 0,
	},
	{
		id: 9,
		SKU: "000010",
		name: "Gloucester 2020-21 Polo 2",
		category: "Off-Field",
		team: "Gloucester Rugby",
		price: 43.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 1,
	},
	{
		id: 10,
		SKU: "000011",
		name: "Gloucester 2020-21 Polo 3",
		category: "Off-Field",
		team: "Gloucester Rugby",
		price: 43.99,
		imageOne: "/images/Product2.jpg",
		imageTwo: "/images/Product1.jpg",
		sale: 1,
	},
	]
}

