export default {
	products: [
	{
		id: 0,
		SKU: "000001",
		name: "Leeds Rhinos Polo 1",
		category: "Off-Field",
		team: "Leeds",
		blurb: "Official Leeds Merchandise",
		price: 29.99,
		imageOne: "/images/product0Image1.jpg",
		imageTwo: "/images/product0Image2.jpg",
		imageThree: "/images/product0Image3.jpg",
		imageFour: "/images/product0Image4.jpg",
		sale: 0,
	},
	{
		id: 1,
		SKU: "000002",
		name: "Gloucester T-Shirt 1",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 24.99,
		imageOne: "/images/product1Image1.jpg",
		imageTwo: "/images/product1Image2.jpg",
		imageThree: "/images/product1Image3.jpg",
		imageFour: "/images/product1Image4.jpg",
		sale: 0,
	},
	{
		id: 2,
		SKU: "000003",
		name: "Gloucester T-Shirt 2",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 24.99,
		imageOne: "/images/product2Image1.jpg",
		imageTwo: "/images/product2Image4.jpg",
		imageThree: "/images/product2Image3.jpg",
		imageFour: "/images/product2Image1.jpg",
		sale: 0,
	},
	{
		id: 3,
		SKU: "000004",
		name: "Doncaster Jacket 1",
		category: "Off-Field",
		team: "Doncaster",
		blurb: "Official Doncaster Merchandise",
		price: 54.99,
		imageOne: "/images/product3Image1.jpg",
		imageTwo: "/images/product3Image2.jpg",
		imageThree: "/images/product3Image3.jpg",
		imageFour: "/images/product3Image4.jpg",
		sale: 0,
	},
	{
		id: 4,
		SKU: "000005",
		name: "Gloucester Polo 1",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 34.99,
		imageOne: "/images/product4Image1.jpg",
		imageTwo: "/images/product4Image2.jpg",
		imageThree: "/images/product4Image3.jpg",
		imageFour: "/images/product4Image4.jpg",
		sale: 0,
	},
	{
		id: 5,
		SKU: "000006",
		name: "Gloucester 2020-21 Polo 2",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 34.99,
		imageOne: "/images/product5Image1.jpg",
		imageTwo: "/images/product5Image2.jpg",
		imageThree: "/images/product5Image3.jpg",
		imageFour: "/images/product5Image4.jpg",
		sale: 0,
	},
	{
		id: 6,
		SKU: "000007",
		name: "Generic Tee 1",
		category: "Off-Field",
		team: "Generic",
		blurb: "High Quality T-shirt",
		price: 16.99,
		imageOne: "/images/product6Image1.jpg",
		imageTwo: "/images/product6Image2.jpg",
		imageThree: "/images/product6Image3.jpg",
		imageFour: "/images/product6Image4.jpg",
		sale: 1,
	},
	{
		id: 7,
		SKU: "000008",
		name: "Gloucester T-shirt 3",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 29.99,
		imageOne: "/images/product7Image1.jpg",
		imageTwo: "/images/product7Image2.jpg",
		imageThree: "/images/product7Image3.jpg",
		imageFour: "/images/product7Image4.jpg",
		sale: 0,
	},
	{
		id: 8,
		SKU: "000009",
		name: "Singlet 1",
		category: "Off-Field",
		team: "Sale",
		blurb: "High Quality Sportswear",
		price: 3.99,
		imageOne: "/images/product8Image1.jpg",
		imageTwo: "/images/product8Image2.jpg",
		imageThree: "/images/product8Image3.jpg",
		imageFour: "/images/product8Image4.jpg",
		sale: 0,
	},
	{
		id: 9,
		SKU: "000010",
		name: "Gloucester Shorts 1",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 22.99,
		imageOne: "/images/product9Image1.jpg",
		imageTwo: "/images/product9Image2.jpg",
		imageThree: "/images/product9Image3.jpg",
		imageFour: "/images/product9Image4.jpg",
		sale: 0,
	},
	{
		id: 10,
		SKU: "000011",
		name: "Gloucester Tee 4",
		category: "Off-Field",
		team: "Gloucester",
		blurb: "Official Gloucester Merchandise",
		price: 31.99,
		imageOne: "/images/product10Image1.jpg",
		imageTwo: "/images/product10Image2.jpg",
		imageThree: "/images/product10Image3.jpg",
		imageFour: "/images/product10Image4.jpg",
		sale: 0,
	},
	]
}

